module.exports = {
    testEnvironment: 'node',
    testMatch: ['**/test/**/*.test.js'],
    transform: {},
    moduleNameMapper: {
        '^~/(.*)$': '<rootDir>/$1',
        '^@ostro/support/(.*)$': '<rootDir>/../support/$1',
        '^@ostro/support$': '<rootDir>/../support',
        '^@ostro/contracts/(.*)$': '<rootDir>/../contracts/$1',
        '^@ostro/contracts$': '<rootDir>/../contracts',
        '^@ostro/container/(.*)$': '<rootDir>/../container/$1',
        '^@ostro/container$': '<rootDir>/../container',
        '^@ostro/filesystem/(.*)$': '<rootDir>/../filesystem/$1',
        '^@ostro/filesystem$': '<rootDir>/../filesystem/filesystemManager.js',
        '^@ostro/database/(.*)$': '<rootDir>/../database/$1',
        '^@ostro/database$': '<rootDir>/../database',
        '^@ostro/router/(.*)$': '<rootDir>/../router/$1',
        '^@ostro/router$': '<rootDir>/../router',
        '^@ostro/foundation/(.*)$': '<rootDir>/../foundation/$1',
        '^@ostro/foundation$': '<rootDir>/../foundation/application.js',
        '^@ostro/console/(.*)$': '<rootDir>/../console/$1',
        '^@ostro/console$': '<rootDir>/../console',
        '^@ostro/cache/(.*)$': '<rootDir>/../cache/$1',
        '^@ostro/cache$': '<rootDir>/../cache',
        '^@ostro/session/(.*)$': '<rootDir>/../session/$1',
        '^@ostro/session$': '<rootDir>/../session',
        '^@ostro/cookie/(.*)$': '<rootDir>/../cookie/$1',
        '^@ostro/cookie$': '<rootDir>/../cookie',
        '^@ostro/auth/(.*)$': '<rootDir>/../auth/$1',
        '^@ostro/auth$': '<rootDir>/../auth',
        '^@ostro/http/(.*)$': '<rootDir>/../http/$1',
        '^@ostro/http$': '<rootDir>/../http',
        '^@ostro/encryption/(.*)$': '<rootDir>/../encryption/$1',
        '^@ostro/encryption$': '<rootDir>/../encryption',
        '^@ostro/validation/(.*)$': '<rootDir>/../validation/$1',
        '^@ostro/validation$': '<rootDir>/../validation',
        '^@ostro/view/(.*)$': '<rootDir>/../view/$1',
        '^@ostro/view$': '<rootDir>/../view',
        '^@ostro/logger/(.*)$': '<rootDir>/../logger/$1',
        '^@ostro/logger$': '<rootDir>/../logger',
        '^@ostro/event/eventServiceProvider$': '<rootDir>/../foundation/test/mocks/eventServiceProvider.js',
        '^@ostro/server/request$': '<rootDir>/../foundation/test/mocks/serverRequest.js',
        '^@ostro/server/response$': '<rootDir>/../foundation/test/mocks/serverResponse.js'
    },
    collectCoverage: true,
    coverageDirectory: 'coverage',
    coverageReporters: ['text', 'lcov', 'clover'],
    collectCoverageFrom: [
        '<rootDir>/app/**/*.js',
        '<rootDir>/bootstrap/app.js',
        '<rootDir>/routes/**/*.js',
        '<rootDir>/database/migrations/**/*.js',
        '<rootDir>/database/seeders/**/*.js',
        '!<rootDir>/node_modules/**',
        '!<rootDir>/test/**',
        '!<rootDir>/coverage/**'
    ]
};
